# Generated by Django 2.1.2 on 2018-10-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0002_auto_20181022_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variete',
            old_name='desc',
            new_name='des',
        ),
    ]
