# Generated by Django 2.1.2 on 2018-10-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0005_auto_20181023_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variete',
            old_name='des',
            new_name='desc',
        ),
    ]
