# Generated by Django 2.1.2 on 2018-10-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0006_auto_20181023_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variete',
            old_name='desc',
            new_name='des',
        ),
    ]
