# Generated by Django 2.1.2 on 2018-10-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0007_auto_20181023_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variete',
            old_name='des',
            new_name='desc',
        ),
    ]
