# Generated by Django 2.1.2 on 2018-10-31 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0008_auto_20181023_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potno', models.CharField(max_length=5)),
                ('typepot', models.CharField(max_length=20)),
                ('diampot', models.CharField(max_length=20)),
                ('hautpot', models.CharField(max_length=20)),
                ('fk_Variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdb.Variete')),
            ],
        ),
    ]
