# Generated by Django 2.1.2 on 2018-10-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdb', '0009_pot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pot',
            old_name='potno',
            new_name='potid',
        ),
    ]
